### ISSUE TITLE
Can I create a High contrast version of it?

### ISSUE THREAD

**Issue by 5jubsPRO** [SpartanJ/WhatsApp-Dark#1]
I have a variation in high contrast.
Can i share with you guys?

**Comment by SpartanJ** [comment]
Hi!
The problem with that is that I would have to maintain two different versions of the style, and I don't have any intention of doing that since it's a style that I basically maintain for my own use. I recommend you to just fork the style and maintain that version by yourself. If you do that just send me the repo URL and I can link your version in the README file.

**Comment by 5jubsPRO** [comment]
Perfect, I'm gonna do that thank's!

**Comment by 5jubsPRO** [comment]
The fork is in https://github.com/5jubsDelta/WhatsApp-Dark
